import mongoose from 'mongoose';

// Define the schema for the Interaction collection
const interactionSchema = new mongoose.Schema({
    // Create a reference to the User who this interaction belongs to.
    // This links each interaction to a specific caregiver's account.
    user: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        ref: 'User', 
    },
    // The text transcribed from the student's voice
    transcribedText: { type: String, required: true },
    // The emotion detected from the student's voice
    detectedEmotion: { type: String, default: 'unknown' },
    // The text response generated by the AI
    responseText: { type: String, required: true },
    topic: { type: String, default: 'General' }
}, {
    timestamps: true, // Automatically add 'createdAt' and 'updatedAt' fields
});

// Create the Mongoose model from the schema
const Interaction = mongoose.model('Interaction', interactionSchema);
export default Interaction;